version: '3'
services:
  webprint:
    image: gitlab.hfk.whka.de:5050/netzwerkteam/web-print
    ports:
      - 100.118.1.21:80:36657
      - 100.118.1.21:631:631
    environment:
      - ADMIN_PASSWORD=cupsadmin
    volumes:
      - ./cups/:/etc/cups/
      - ./certs/:/app/certs/
